nabwes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from .views import home, about, contact, gallery,newsletter_subscribe, blog, events, service, event_detail, registration_success, causes, donation, custom_404_test, test,members, executives,  blog_view, parliamentary

urlpatterns = [
    path('', home, name='home'),
    path('test/', test),
    path("blog/", blog, name='blog'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('events/', events, name='events'),
    path('gallery/', gallery, name='gallery'),
    path('service/', service, name='service'),
    path('causes/', causes, name='causes'),
    path('executives/', executives, name='executives'),
    path('parliamentary/', parliamentary, name='team_spc'),
    path('donation/', donation, name='donation'),
    path('error_404/', custom_404_test, name='error_404'),
    path('members/', members, name='members'),
    path('blog/<int:pk>/', blog_view, name="view"),
    path('<int:event_id>/', event_detail, name='event_detail'),
    path('registration-success/<int:registration_id>/', registration_success, name='registration_success'),
    path('subscribe/', newsletter_subscribe, name="newsletter_subscribe")
]

webapp/models.py
from django.db import models
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from PIL import Image

class Blog(models.Model):
    img_url =  models.ImageField(upload_to="images/")
    title = models.CharField(max_length=1000)
    authour = models.CharField(max_length=500)
    desc = models.CharField(max_length=500, default="")
    authour_img = models.ImageField(default="", )
    # tags = TaggableManager()
    body = RichTextField(blank=True, null=True)
    date = models.DateField()
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    
    def comment_count(self):
        return self.comments.filter(active=True).count()


class Event(models.Model):
    title= models.CharField(default="", max_length=1024)
    venue = models.CharField(max_length=1024, default="")
    desc = models.CharField(max_length=500, default="")
    body = RichTextField(blank=True, null=True)
    capacity = models.PositiveIntegerField(default=200, null=True)
    event_img_url= models.ImageField()
    date = models.DateField(null=True)

    def __str__(self):
        return self.title

class Registration(models.Model):
    event = models.ForeignKey(Event, related_name='registrations', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20, blank=True, null=True)
    registered_at= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.event.title}"

class EventPass(models.Model):
    registration = models.OneToOneField(Registration, on_delete=models.CASCADE, related_name='event_pass')
    pass_code = models.CharField(max_length=12, unique= True)
    

    def __str__(self):
        return f"Pass for {self.registration.full_name}"
    
class Sponsor(models.Model):
    event = models.ForeignKey(Event, related_name='sponsors', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='sponsors/')
    website_or_social_url= models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name
    
class Gallery(models.Model):
    title = models.CharField(default="", max_length=1024)
    desc= models.CharField(default="", max_length=500)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.title
    

class GalleryImage(models.Model):
    gallery = models.ForeignKey(Gallery, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='gallery_images/')
    caption = models.CharField(max_length=100, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        # Set maximum dimensions
        max_width, max_height = 800, 800

        if img.width > max_width or img.height > max_height:
            # Resize the image
            img.thumbnail((max_width, max_height))
            img.save(self.image.path)
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=70)
    email = models.EmailField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

class Executives(models.Model):
    name = models.CharField(max_length=500)
    position = models.CharField(max_length=500)
    image= models.ImageField(upload_to="gallery_images/")
    facebook_link = models.CharField(max_length=2000)
    linkedIn_link = models.CharField(max_length=2000)
    twitter_link = models.CharField(max_length=2000)

class Parliamentary(models.Model):
    name = models.CharField(max_length=500)
    position = models.CharField(max_length=500)
    image= models.ImageField(upload_to="gallery_images/")
    facebook_link = models.CharField(max_length=2000)
    linkedIn_link = models.CharField(max_length=2000)
    twitter_link = models.CharField(max_length=2000)

class Subscriber(models.Model):
    email = models.EmailField(unique=True)
    subscried_at= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

webapp/forms.py
from django import forms
from .models import Comment, Registration,Subscriber

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =['text', 'email', 'author']

class RegistrationForm(forms.ModelForm):
    class Meta:
        model= Registration
        fields= ['full_name', 'email', 'phone']

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your email',
            })
        }

webapp/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from .models import Gallery,Subscriber, Blog, Event, Comment, Registration, EventPass, Executives, Parliamentary
from .forms import CommentForm, RegistrationForm, SubscriberForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages
import random
import string

import qrcode
import base64
from io import BytesIO
from PIL import Image

def home(request):
    blog = Blog.objects.all().order_by('-id')[:8]
    carousel = Blog.objects.all().order_by('-id')[:3]
    event = Event.objects.all().order_by('-id')[:5]
    gallery = Gallery.objects.all().order_by('-id')[:4]

    return render(request, 'index.html', {'blogs': blog, 'carousel': carousel, 'gallery': gallery, 'events':event})

def newsletter_subscribe(request):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'message': 'Invalid email address'})
    return JsonResponse({'success': False, 'message': 'Invalid request'})


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def blog(request):
    blog = Blog.objects.all()
    paginator = Paginator(blog, 12)
    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        paginated_posts = paginator.page(1)
    except EmptyPage:
        paginated_posts = paginator.page(paginator.num_pages)

    return render(request, 'blog.html', {'blog':paginated_posts})

def blog_view(request, pk):
    global comment_form
    blog = get_object_or_404(Blog, pk=pk)
    # view count
    if not hasattr(blog, 'view_count'):
        blog = Blog.objects.get(pk=pk)
    
    blog.view_count += 1
    blog.save()

    # comments
    comments = Comment.objects.filter(blog=blog)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog = blog
            comment.save()

    else:
        comment_form = CommentForm()
    return render(request, 'blog_view.html', {'blogs':blog, 'comments': comments, 'form':comment_form})


def events(request):
    events = Event.objects.all()
    return render(request, 'events.html', {'events':events})


def event_detail(request, event_id):
    event = get_object_or_404(Event, id= event_id)
    sponsors = event.sponsors.all()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            registration = form.save(commit=False)
            registration.event = event
            # if event.registrations.count() < event.capacity:
            registration.save()
            pass_code = ''.join(random.choices(string.ascii_uppercase + string.digits, k= 8))
            EventPass.objects.create(registration=registration, pass_code=pass_code)
            return redirect('registration_success', registration_id= registration.id)
            # else:
            #     return render(request, 'events_full.html', {'event':event})
    else:
        form = RegistrationForm()
        return render(request, 'event_d.html', {'event':event, 'form':form, 'sponsors':sponsors, 'event_date': event.date.strftime('%Y-%m-%dT%H:%M:%S'),})


def registration_success(request, registration_id):
    registration = get_object_or_404(Registration, id= registration_id)
   
    # Generate QR code

    # Generate QR code data
    qr_data = f"Event: {registration.event.title}\nName: {registration.full_name}\nPass Code: {registration.event_pass.pass_code}"

    # Create QR code image
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=10,
        border=4,
    )
    qr.add_data(qr_data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    # Convert QR code to base64
    buffer = BytesIO()
    img.save(buffer, format="PNG")
    qr_base64 = base64.b64encode(buffer.getvalue()).decode()

    return render(request, 'registration_success.html', {'registration': registration, 'qr_code': qr_base64})


def gallery(request):
    galleries= Gallery.objects.all()
    paginator = Paginator(galleries, 4)
    page = request.GET.get('page')
    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        paginated_posts = paginator.page(1)
    except EmptyPage:
        paginated_posts = paginator.page(paginator.num_pages)
    return render(request, 'gallery.html', {'galleries': paginated_posts})

def test(request):
    return render(request, 'gallery_test.html')

def service(request):
    return render(request, 'service.html')


def causes(request):
    return render(request, 'causes.html')


def executives(request):
    executives = Executives.objects.all()
    return render(request, 'team_sec.html', {'executives':executives})


def parliamentary(request):
    parliamentary = Parliamentary.objects.all()
    return render(request, 'team_spc.html', {'parliamentary': parliamentary})


def donation(request):
    return render(request, 'donation.html')

def custom_404_test(request):
    return HttpResponseNotFound(render(request, '404.html'))

def members(request):
    return render(request, 'members.html')


def subscribe(request):
    if request.method == 'POST':
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,  'Thank you for subscribing to our newsletter!')
            return redirect('subscribe')
        else:
            messages.error(request, 'Invalid email. Please Try again')
    else:
        form = SubscriberForm()
    return render(request, 'base.html', {'form': form})

webapp/templates/blog.html
{% extends "base.html" %}
{%load static%}
{% block title %} NABWES | Blogs {% endblock %}

{% block content %}


        <!-- Header Start -->
        <div class="container-fluid bg-breadcrumb">
            <div class="container text-center py-5" style="max-width: 900px;">
                <h3 class="text-white display-3 mb-4">Latest News & Blog</h1>
                <p class="fs-5 text-white mb-4">Help today because tomorrow you may be
                    the one who needs more helping!</p>
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Pages</a></li>
                    <li class="breadcrumb-item active text-white">Blog</li>
                </ol>
            </div>
        </div>
        <!-- Header End -->

        <!-- Blog Start -->
        <div class="container-fluid blog py-5">
            <div class="container py-5">
                <div class="text-center mx-auto pb-5" style="max-width: 800px;">
                    <h5 class="text-uppercase text-primary">Latest News & Blog</h5>
                    <h1 class="mb-0">Here is the latest news and trending about NABWES!
                    </h1>
                </div>
                <div class="row g-4">
                    {%for item in blog%}
                    <div class="col-lg-6 col-xl-3">
                        <div class="blog-item">
                            <div class="blog-img">
               
                <img src="{{item.img_url.url}}" class="img-fluid w-100"  style="height: 300px" alt="">
                                <div class="blog-info">
                                    <span><i class="fa fa-clock"></i>{{item.date}}</span>
                                    <div class="d-flex">
                                        <span class="me-3"> {{item.view_count}}<i class="fa fa-heart"></i></span>
                                        <a href="#" class="text-white">{{item.comment_count}} <i class="fa fa-comment"></i></a>
                                    </div>
                                </div>
                                <div class="search-icon">
                                    <a href="{{item.img_url.url}}" data-lightbox="Blog-1" class="my-auto"><i class="fas fa-search-plus btn-primary text-white p-3"></i></a>
                                </div>
                            </div>
                            <div class="text-dark border p-4 ">
                                <h4 class="mb-4">{{item.title}}</h4>
                                <p class="mb-4">{{item.desc}}</p>
                                <a class="btn-hover-bg btn btn-primary text-white py-2 px-4" href="{%url 'view' item.pk%}">Read More</a>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                                 </div>
            </div>
        </div>
        <!-- Blog End -->
        <nav aria-label="Blog Pagination">
            <ul class="pagination justify-content-center">
                {% if blog.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ blog.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
    
                {% for num in blog.paginator.page_range %}
                    {% if num == blog.number %}
                        <li class="page-item active"><a class="page-link">{{ num }}</a></li>
                    {% elif num > blog.number|add:'-3' and num < blog.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ blog.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ blog.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
{%endblock%}

webapp/templates/blog_view.html
{%extends 'base.html' %} {%block content %} <br /><br /><br />
{%load static%}
<div class="container my-4">
  <!-- Blog Post -->
  <div class="card mb-4">
    <img src="{{blogs.img_url.url}}" class="card-img-top" alt="Blog Image" />
    <div class="card-body">
      <h1 class="card-title">{{blogs.title}}</h1>
      <div class="d-flex align-items-center mb-3">
        <img
          src="{{blogs.authour_img.url}}"
          class="rounded-circle me-3"
          alt="Author Image"
          style="height: 50px; width: 50px"
        />
        <div>
          <h6 class="mb-0">By <strong>{{blogs.authour}}</strong></h6>
          <small class="text-muted"
            >Published on <strong>{{blogs.date}}</strong></small
          >
        </div>
      </div>
      <p class="card-text">{{blogs.body| safe}}</p>
    </div>
  </div>

  <!-- Comments Section -->
  <div class="comments-section mb-4">
    <h2>Comments</h2>
    <!-- Comment 1 -->
    {%for comment in comments%}
    <div class="mb-3">
      <div class="d-flex align-items-start">
        <img
          src="https://via.placeholder.com/50"
          class="rounded-circle me-3"
          alt="User Avatar"
        />
        <div>
          <h6 class="fw-bold mb-0">{{comment.author}}</h6>
          <small class="text-muted"
            >Posted on <span>{{comment.created_date}}</span></small
          >
          <p class="mb-0">{{comment.text}}</p>
        </div>
      </div>
    </div>
    {%endfor%}
    <!-- Comment 2
    <div class="mb-3">
      <div class="d-flex align-items-start">
        <img
          src="https://via.placeholder.com/50"
          class="rounded-circle me-3"
          alt="User Avatar"
        />
        <div>
          <h6 class="fw-bold mb-0">Jane Smith</h6>
          <small class="text-muted">Posted on Nov 28, 2024</small>
          <p class="mb-0">Thanks for sharing! This was very helpful.</p>
        </div>
      </div>
    </div>
  </div> -->
    <!-- <form method="post">{{form.as_p}}</form> -->
    <!-- Comment Form -->
    <div class="comment-form">
      <h2>Leave a Comment</h2>
      <form method="post">
        {%csrf_token%}
        <div class="mb-3">
          <label for="name" class="form-label">Name</label>
          <input
            type="text"
            class="form-control"
            name="author"
            id="id_author"
            placeholder="Your Name"
            required
          />
        </div>
        <div class="mb-3">
          <label for="email" class="form-label">Email</label>
          <input
            type="email"
            class="form-control"
            id="id_email"
            name="email"
            placeholder="Your Email"
            required
          />
        </div>
        <div class="mb-3">
          <label for="comment" class="form-label">Comment</label>
          <textarea
            class="form-control"
            id="id_text"
            rows="4"
            placeholder="Your Comment"
            name="text"
            required
          ></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit Comment</button>
      </form>
    </div>
  </div>
</div>

{%endblock%}

webapp/templates/council-team.html
{% extends "base.html" %}
{%load static%}
{% block title %} NABWES | Team {% endblock %}

{% block content %}
        <!-- Team Start -->
        <div class="container-fluid team py-5">
            <div class="container py-5">
                <div class="text-center mx-auto pb-5 wow fadeInUp" data-wow-delay="0.2s" style="max-width: 800px;">
                    <h4 class="text-primary">Our Team</h4>
                    <h1 class="display-5 mb-4">Meet Our Advisers</h1>
                    <p class="mb-0">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur adipisci facilis cupiditate recusandae aperiam temporibus corporis itaque quis facere, numquam, ad culpa deserunt sint dolorem autem obcaecati, ipsam mollitia hic.
                    </p>
                </div>
                <div class="row g-4">
                    <div class="col-md-6 col-lg-6 col-xl-3 wow fadeInUp" data-wow-delay="0.2s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'img/causes-1.jpg' %}" class="img-fluid" alt="">
                            </div>
                            <div class="team-title">
                                <h4 class="mb-0">David James</h4>
                                <p class="mb-0">Profession</p>
                            </div>
                            <div class="team-icon">
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-linkedin-in"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-0" href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6 col-xl-3 wow fadeInUp" data-wow-delay="0.4s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'img/causes-2.jpg' %}" class="img-fluid" alt="">
                            </div>
                            <div class="team-title">
                                <h4 class="mb-0">David James</h4>
                                <p class="mb-0">Profession</p>
                            </div>
                            <div class="team-icon">
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-linkedin-in"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-0" href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6 col-xl-3 wow fadeInUp" data-wow-delay="0.6s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'img/causes-3.jpg' %}" class="img-fluid" alt="">
                            </div>
                            <div class="team-title">
                                <h4 class="mb-0">David James</h4>
                                <p class="mb-0">Profession</p>
                            </div>
                            <div class="team-icon">
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-linkedin-in"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-0" href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6 col-xl-3 wow fadeInUp" data-wow-delay="0.8s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'img/causes-1.jpg' %}" class="img-fluid" alt="">
                            </div>
                            <div class="team-title">
                                <h4 class="mb-0">David James</h4>
                                <p class="mb-0">Profession</p>
                            </div>
                            <div class="team-icon">
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-3" href=""><i class="fab fa-linkedin-in"></i></a>
                                <a class="btn btn-primary btn-sm-square rounded-circle me-0" href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Team End -->
{%endblock%}

webapp/templates/event_d.html
{%extends 'base.html'%} {%block content%}
<style>
  #countdown {
      text-align: center;
      background: #f9f9f9;
      padding: 20px;
      border-radius: 10px;
      margin-top: 20px;
  }
  #timer {
      font-size: 2rem;
      color: #F8B864;
  }
</style>

<div class="container my-5">
  <br><br><br> 
  <div class="row">
    <!-- Event Details Section -->
    <div class="col">
      <img src="{{event.event_img_url.url}}" class="card-img-top" alt="Blog Image" />
      <h1 class="display-4">{{ event.name }}</h1>
      <p class="lead">{{ event.description }}</p>
      <hr />
      <p><strong>Date:</strong> {{ event.date|date }}</p>
      <p><strong>Location:</strong> {{ event.venue }}</p>
      <p><strong>Capacity:</strong> {{ event.capacity }}</p>

      <div>{{event.body|safe}}</div>
        <!-- Attendee Count with Animation -->
        <div class="mt-4">
          <h3>Registered Attendees</h3>
          <p class="display-5">
              <span id="attendeeCount" data-count="{{ event.registrations.count }}">0</span>
          </p>
      </div>
      </div>

      {% if event.registrations.count >= event.capacity %}
      <div class="alert alert-danger mt-3">This event is fully booked!</div>
      {% endif %}

     <!-- Countdown Timer -->
    <div id="countdown" class="mt-4">
      <h3>Time Left:</h3>
      <p id="timer" class="display-5">Loading...</p>
  </div>
</div>

    <!-- Sponsors Section -->
    <div class="mt-5">
      <h3>Sponsors</h3>
      <div class="row">
          {% for sponsor in sponsors %}
              <div class="col-md-3 col-sm-6 text-center mb-4">
                  <a href="{{ sponsor.website }}" target="_blank">
                      <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}" class="img-fluid" style="max-height: 150px;">
                  </a>
                  <p>{{ sponsor.name }}</p>
              </div>
          {% empty %}
              <p>No sponsors for this event yet.</p>
          {% endfor %}
      </div>

    <!-- Registration Form Section -->
    <div class="col-lg-4">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Register Now</h4>
          <form method="post">
            {% csrf_token %} 
            <input type="text" name="full_name" placeholder="Full Name" class="form-control"maxlength="255" required id="id_full_name">
          <br>  <input type="email" placeholder="Email" class="form-control" name="email" maxlength="254" required id="id_email">
           <br> <input type="text" name="phone" placeholder="Phone" class="form-control" maxlength="20" id="id_phone">
          <br>  <button
              type="submit"
              class="btn btn-primary w-100"  {%if  event.registrations.count >= event.capacity %} disabled {% endif %}> Register
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
      const counter = document.getElementById('attendeeCount');
      if (counter) {
          const countTo = parseInt(counter.getAttribute('data-count'), 10);

          let count = 0;
          const duration = 1000; // Duration of animation in milliseconds
          const intervalTime = 15; // Update every 15ms
          const steps = Math.ceil(duration / intervalTime); // Number of steps
          const increment = countTo / steps;

          const interval = setInterval(() => {
              count += increment;
              if (count >= countTo) {
                  counter.textContent = countTo;
                  clearInterval(interval);
              } else {
                  counter.textContent = Math.floor(count);
              }
          }, intervalTime);
      }
  });
  document.addEventListener('DOMContentLoaded', function () {
    const eventDate = new Date("{{ event_date }}").getTime(); // Event date and time in JS

    function updateCountdown() {
        const now = new Date().getTime();
        const timeLeft = eventDate - now;

        if (timeLeft <= 0) {
            document.getElementById("timer").textContent = "Event Started!";
            clearInterval(interval);
            return;
        }

        const days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
        const hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        const minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
        const seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);

        document.getElementById("timer").textContent =
            `${days} Days ${hours} Hours ${minutes} Minutes ${seconds} Seconds`;
    }

    // Update countdown every 1 second
    const interval = setInterval(updateCountdown, 1000);
    updateCountdown(); // Run immediately
});
</script>

  {%endblock%}

webapp/templates/event_full.html
{%extends 'base.html'%} {%block content%}
<div class="container">
  <h1>{{ event.name }}</h1>
  <p>Sorry, this event is fully booked.</p>
</div>
{%endblock%}